# Generated by Django 4.2.1 on 2025-01-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'устройство', 'verbose_name_plural': 'устройства'},
        ),
        migrations.AlterModelOptions(
            name='devicecompany',
            options={'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
        migrations.AlterModelOptions(
            name='deviceseries',
            options={'verbose_name': 'серия', 'verbose_name_plural': 'серии'},
        ),
    ]
