# Generated by Django 4.2.1 on 2025-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price_from_1',
            field=models.PositiveBigIntegerField(verbose_name='Цена от 1 шт'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price_from_20',
            field=models.PositiveBigIntegerField(verbose_name='Цена от 20 шт'),
        ),
    ]
