# Generated by Django 4.2.1 on 2025-01-19 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_price_from_1_alter_device_price_from_20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price_from_1',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена от 1 шт'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price_from_20',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена от 20 шт'),
        ),
    ]
