# Generated by Django 4.2.1 on 2025-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_price_from_1_alter_device_price_from_20'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'series'), name='unique_device_name_per_series'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_model_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='deviceseries',
            constraint=models.UniqueConstraint(fields=('name', 'model'), name='unique_series_name_per_model'),
        ),
    ]
