# Generated by Django 4.2.1 on 2025-04-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_unique_device_name_per_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecompany',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'series'), name='unique_device_name_per_series'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_model_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='deviceseries',
            constraint=models.UniqueConstraint(fields=('name', 'model'), name='unique_series_name_per_model'),
        ),
    ]
