# Generated by Django 4.2.1 on 2025-05-20 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_remove_device_unique_device_name_per_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_import_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 11, 48, 32, 572114, tzinfo=datetime.timezone.utc), verbose_name='Дата последнего импорта'),
        ),
    ]
