# Generated by Django 4.2.1 on 2025-05-20 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_last_import_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_import_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего импорта'),
        ),
    ]
