# Generated by Django 4.2.1 on 2025-05-20 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_last_import_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-last_import_time'], 'verbose_name': 'устройство', 'verbose_name_plural': 'устройства'},
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ['-last_import_time'], 'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
        migrations.AlterModelOptions(
            name='deviceseries',
            options={'ordering': ['-last_import_time'], 'verbose_name': 'серия', 'verbose_name_plural': 'серии'},
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='last_import_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего импорта'),
        ),
        migrations.AddField(
            model_name='deviceseries',
            name='last_import_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего импорта'),
        ),
    ]
