# Generated by Django 4.2.1 on 2025-02-03 16:00

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, default=None, null=True, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(db_index=True, default=None, max_length=70, null=True, unique=True, verbose_name='Имя пользователя')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Номер телефона')),
                ('bot_start_link', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Ссылка для запуска бота')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Количество')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='telegram_users.telegramuser')),
            ],
            options={
                'verbose_name': 'элемент корзины',
                'verbose_name_plural': 'корзина',
            },
        ),
    ]
