# Generated by Django 4.2.1 on 2025-01-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_alter_cartitem_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'элемент корзины', 'verbose_name_plural': 'корзина'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram пользователь', 'verbose_name_plural': 'Telegram пользователи'},
        ),
    ]
