# Generated by Django 4.2.1 on 2025-01-07 13:48

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('number', models.BigIntegerField(verbose_name='Номер заказа')),
                ('devices', models.JSONField(default=list, verbose_name='Устройства')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
