# Generated by Django 4.2.1 on 2025-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ARRIVED', 'Прибыл'), ('BOUGHT', 'Куплен'), ('CHANGED', 'Изменён'), ('CANCELED', 'Отменён')], db_index=True, default='ARRIVED', max_length=11, verbose_name='Статус'),
        ),
    ]
