# Generated by Django 4.2.1 on 2025-02-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
