# Generated by Django 4.2.1 on 2025-02-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='general_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
