# Generated by Django 4.2.1 on 2025-02-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_price_orderitem_general_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='general_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_for_one',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Цена за 1 шт'),
        ),
    ]
