# Generated by Django 4.2.1 on 2025-01-07 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ARRIVED', 'Прибыл'), ('BOUGHT', 'Куплен'), ('ASSEMBLED', 'Собран'), ('КNOCKED_OUT', 'Выбит'), ('CANCEL', 'Отменён')], db_index=True, default='ARRIVED', max_length=11, verbose_name='Статус'),
        ),
    ]
