# Generated by Django 4.2.1 on 2025-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ARRIVED', 'Прибыл'), ('BOUGHT', 'Куплен'), ('ASSEMBLED', 'Собран'), ('КNOCKED_OUT', 'Выбит'), ('CANCELED', 'Отменён')], db_index=True, default='ARRIVED', max_length=11, verbose_name='Статус'),
        ),
    ]
