# Generated by Django 4.2.1 on 2025-03-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_unique_device_name_per_series_and_more'),
        ('orders', '0005_remove_orderitem_general_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='device_name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Название устройства'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='Устройство'),
        ),
    ]
