# Generated by Django 4.2.1 on 2025-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_receiver_telegram_id', models.BigIntegerField(verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
